### PR TITLE
Added a validator script for checking data dictionary files.

### PR DESCRIPTION
**Pull request by victorSRI**

### CODE REVIEW

**Comment by nicholsn** [comment]
@victorSRI, I sent you a PR that reformats the script with the python coding style I am familiar with. I can merge this once you've merged https://github.com/victorSRI/redcap_rdf/pull/1

**Comment by nicholsn** [comment]
@victorSRI let me know when this is ready to merge

**Comment by victorSRI** [comment]
@nicholsn should be good to go, as long as edd210221b makes it in

**Comment by nicholsn** [comment]
cool, thanks for catching that one

**Pull request merged**
